# Generated by Django 5.1.2 on 2024-10-22 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, verbose_name='delivery zone'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('dp', models.ImageField(upload_to='users/dp/%Y/%m/%d/', verbose_name='profile picture')),
                ('nid', models.CharField(max_length=50, verbose_name='nid')),
                ('nid_front', models.ImageField(upload_to='verification/nid/%Y/%m/%d/', verbose_name='nid front')),
                ('nid_back', models.ImageField(upload_to='verification/nid/%Y/%m/%d/', verbose_name='nid back')),
                ('driving_license', models.CharField(blank=True, max_length=100, null=True, verbose_name='driving license')),
                ('driving_license_front', models.ImageField(upload_to='verification/dl/%Y/%m/%d/', verbose_name='driving license front')),
                ('driving_license_back', models.ImageField(upload_to='verification/dl/%Y/%m/%d/', verbose_name='driving license back')),
                ('is_verified', models.BooleanField(default=False)),
                ('permanent_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_address', to='core.address', verbose_name='raider permanent address')),
                ('present_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='present_address', to='core.address', verbose_name='raider present address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('dp', models.ImageField(blank=True, null=True, upload_to='vehicle/%Y/%m/%d/', verbose_name='vehicle picture')),
                ('vehicle_type', models.CharField(choices=[('car', 'CAR'), ('bike', 'BIKE'), ('cycle', 'CYCLE'), ('walker', 'WALKER')], default='bike', max_length=20, verbose_name='vehicle type')),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='registration number')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='brand')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
