# Generated by Django 5.1.2 on 2024-10-26 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_user'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nominee_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominee_address', to='core.address', verbose_name='nominee address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nominee_contact',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='nominee contact'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nominee_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nominee name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nominee_relationship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nominee relationship'),
        ),
    ]
