# Generated by Django 5.1.2 on 2024-10-28 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_nominee_address_profile_nominee_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raider_vehicle', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
