# Generated by Django 5.0.3 on 2025-02-28 11:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_is_active_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverWorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date on which the driver worked', verbose_name='Work date')),
                ('start_time', models.TimeField(help_text="Driver's work start time", verbose_name='Start time')),
                ('end_time', models.TimeField(help_text="Driver's work end time", verbose_name='End time')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('missed', 'Missed'), ('partial', 'Partial')], default='completed', help_text='Status of the work day', max_length=20, verbose_name='Work status')),
                ('total_deliveries', models.PositiveIntegerField(default=0, help_text='Total number of deliveries completed on this day', verbose_name='Total Deliveries')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, help_text='Total earnings from deliveries on this day', max_digits=10, verbose_name='Total Earnings')),
                ('total_active_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Total hours the driver was active during the session', max_digits=5, verbose_name='Total Active Hours')),
                ('offline_count', models.PositiveIntegerField(default=0, help_text='Number of times the driver went offline during the session', verbose_name='Offline Count')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to=settings.AUTH_USER_MODEL, verbose_name='Driver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriverSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('weekday', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', help_text='The specific day of the week for this session', max_length=10, verbose_name='Weekday')),
                ('start_time', models.TimeField(help_text="Driver's work start time", verbose_name='Start time')),
                ('end_time', models.TimeField(default=datetime.time(23, 59, 59), help_text="Driver's work end time", verbose_name='End time')),
                ('is_recurring', models.BooleanField(default=False, help_text='Set this session to repeat weekly', verbose_name='Is recurring')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the session is currently active', verbose_name='Is active')),
                ('offline_count', models.PositiveIntegerField(default=0, help_text='Number of times the driver went offline during the session', verbose_name='Offline Count')),
                ('total_active_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Total hours the driver was active during the session', max_digits=5, verbose_name='Total Active Hours')),
                ('last_active_time', models.DateTimeField(blank=True, help_text="Timestamp of the driver's last active state", null=True, verbose_name='Last Active Time')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='driver_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Driver')),
            ],
            options={
                'unique_together': {('user', 'weekday')},
            },
        ),
    ]
