# Generated by Django 5.0.3 on 2025-02-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_driverworkhistory_driversession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverworkhistory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='driverworkhistory',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='driverworkhistory',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='driverworkhistory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='driverworkhistory',
            name='total_active_hours',
        ),
        migrations.AddField(
            model_name='driverworkhistory',
            name='on_time_deliveries',
            field=models.PositiveIntegerField(default=0, help_text='Number of deliveries completed on or before the estimated time', verbose_name='On-Time Deliveries'),
        ),
        migrations.AlterField(
            model_name='driverworkhistory',
            name='offline_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the driver went offline', verbose_name='Offline Count'),
        ),
        migrations.AlterField(
            model_name='driverworkhistory',
            name='total_deliveries',
            field=models.PositiveIntegerField(default=0, help_text='Total number of deliveries completed by the driver', verbose_name='Total Deliveries'),
        ),
        migrations.AlterField(
            model_name='driverworkhistory',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total earnings from deliveries', max_digits=10, verbose_name='Total Earnings'),
        ),
    ]
