# Generated by Django 5.0.3 on 2025-02-28 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_driverworkhistory_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driversession',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='driversession',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='driverworkhistory',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='driverworkhistory',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='driverworkhistory',
            name='total_active_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='driversession',
            name='end_time',
            field=models.TimeField(default=datetime.time(23, 59, 59), verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='driversession',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='driversession',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Is recurring'),
        ),
        migrations.AlterField(
            model_name='driversession',
            name='last_active_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Active Time'),
        ),
        migrations.AlterField(
            model_name='driversession',
            name='offline_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Offline Count'),
        ),
        migrations.AlterField(
            model_name='driversession',
            name='start_time',
            field=models.TimeField(verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='driversession',
            name='total_active_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='driverworkhistory',
            name='offline_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driverworkhistory',
            name='on_time_deliveries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driverworkhistory',
            name='total_deliveries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driverworkhistory',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
