# Generated by Django 5.0.3 on 2025-02-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_driversession_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverworkhistory',
            name='online_duration',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
