# Generated by Django 5.0.3 on 2025-02-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_driverworkhistory_online_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='driversession',
            name='created_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
