# Generated by Django 5.0.3 on 2025-03-12 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_driversession_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driversession',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='driversession',
            name='last_active_time',
        ),
        migrations.AddField(
            model_name='driversession',
            name='first_delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Delivery Time'),
        ),
        migrations.AddField(
            model_name='driversession',
            name='on_time_deliveries',
            field=models.PositiveIntegerField(default=0, verbose_name='On-Time Deliveries'),
        ),
        migrations.AddField(
            model_name='driversession',
            name='total_deliveries',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Deliveries'),
        ),
        migrations.AddField(
            model_name='driversession',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Earnings'),
        ),
        migrations.AlterField(
            model_name='driversession',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='driversession',
            name='end_time',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='driversession',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='driversession',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time'),
        ),
    ]
