# Generated by Django 5.0.3 on 2025-03-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_driversession_is_recurring_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driversession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='driversession',
            name='session_slot',
            field=models.CharField(choices=[('08:00-12:00', '8 AM - 12 PM'), ('12:00-16:00', '12 PM - 4 PM'), ('16:00-20:00', '4 PM - 8 PM'), ('20:00-00:00', '8 PM - 12 AM')], default='08:00-12:00', help_text='The time slot assigned to the session', max_length=15, verbose_name='Session Slot'),
        ),
        migrations.AlterUniqueTogether(
            name='driversession',
            unique_together={('user', 'weekday', 'session_slot')},
        ),
    ]
