# Generated by Django 5.0.3 on 2025-03-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_driversession_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driversession',
            name='first_delivery_time',
        ),
        migrations.RemoveField(
            model_name='driversession',
            name='offline_count',
        ),
        migrations.RemoveField(
            model_name='driversession',
            name='on_time_deliveries',
        ),
        migrations.RemoveField(
            model_name='driversession',
            name='total_active_hours',
        ),
        migrations.RemoveField(
            model_name='driversession',
            name='total_deliveries',
        ),
        migrations.RemoveField(
            model_name='driversession',
            name='total_earnings',
        ),
    ]
