# Generated by Django 5.0.3 on 2025-03-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_driversession_first_delivery_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driversession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='driversession',
            name='start_time',
        ),
    ]
