# Generated by Django 5.0.3 on 2025-03-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_driversession_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driversession',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
    ]
