# Generated by Django 5.0.3 on 2025-04-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_driversession_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='driversession',
            name='last_online_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
