# Generated by Django 5.0.3 on 2025-05-20 05:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_driversession_last_online_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driversession',
            name='weekday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10), default=list, help_text='List of weekdays for this session', size=7, verbose_name='Weekdays'),
        ),
    ]
