# Generated by Django 5.0.3 on 2025-06-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_alter_driversession_weekday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driversession",
            name="session_slot",
            field=models.CharField(
                choices=[
                    ("08:00-12:00", "8 AM - 12 PM"),
                    ("08:00-22:00", "8 AM - 10 PM"),
                    ("12:00-16:00", "12 PM - 4 PM"),
                    ("16:00-20:00", "4 PM - 8 PM"),
                    ("20:00-00:00", "8 PM - 12 AM"),
                ],
                default="08:00-12:00",
                help_text="The time slot assigned to the session",
                max_length=15,
                verbose_name="Session Slot",
            ),
        ),
    ]
