# Generated by Django 5.0.3 on 2025-06-01 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=100)),
                ('street_number', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=20)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('store_banner', models.ImageField(blank=True, null=True, upload_to='store_banners/')),
                ('store_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('salons', 'Salons'), ('hotels', 'Hotels'), ('medicine', 'Medicine')], default='restaurant', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_store_open', models.BooleanField(default=True)),
                ('utensil_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_method', models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup'), ('local_deal', 'Local Deal'), ('dine_in', 'Dine In')], default='delivery', max_length=20)),
                ('payment_methods', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online Payment'), ('wallet', 'Wallet')], default='cash', max_length=50)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='store.address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
