# Generated by Django 5.0.3 on 2025-06-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=50, null=True),
        ),
    ]
