# Generated by Django 5.0.3 on 2025-06-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_latitude_alter_store_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.CharField(default='0.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.CharField(default='0.0', max_length=20),
        ),
    ]
