# Generated by Django 5.0.3 on 2025-06-01 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_store_latitude_alter_store_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='is_store_open',
        ),
        migrations.AddField(
            model_name='store',
            name='is_temporarily_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StoreOperatingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='store.store')),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('store', 'day_of_week')},
            },
        ),
    ]
