# Generated by Django 5.0.3 on 2025-06-01 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_store_is_store_open_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='address',
        ),
        migrations.RemoveField(
            model_name='store',
            name='is_temporarily_closed',
        ),
        migrations.RemoveField(
            model_name='store',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='store',
            name='longitude',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_temporarily_closed', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='store.address')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='store.store')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='storeoperatinghour',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='storeoperatinghour',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='store.location'),
        ),
        migrations.AlterUniqueTogether(
            name='storeoperatinghour',
            unique_together={('location', 'day_of_week')},
        ),
        migrations.RemoveField(
            model_name='storeoperatinghour',
            name='store',
        ),
    ]
