# Generated by Django 5.0.3 on 2025-06-01 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_store_address_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storeoperatinghour',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='store.address'),
        ),
        migrations.AddField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='store',
            name='is_temporarily_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='operating_hours',
            field=models.ManyToManyField(blank=True, help_text='Define the operating hours for each day of the week.', related_name='stores', to='store.storeoperatinghour'),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.RemoveField(
            model_name='storeoperatinghour',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
