# Generated by Django 5.0.3 on 2025-06-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_storeoperatinghour_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
