# Generated by Django 5.0.3 on 2025-06-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_store_latitude_alter_store_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='owner',
        ),
    ]
