# Generated by Django 5.0.3 on 2025-06-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('sold_out', 'Sold Out'), ('unavailable_today', 'Unavailable Today')], default='in_stock', max_length=20),
        ),
    ]
