# Generated by Django 5.0.3 on 2025-06-01 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_menu_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cuisines', to='store.store'),
            preserve_default=False,
        ),
    ]
