# Generated by Django 5.0.3 on 2025-06-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_cuisine_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifier',
            name='requirement',
            field=models.CharField(choices=[('optional', 'Optional'), ('required', 'Required')], default='optional', max_length=20),
        ),
    ]
