# Generated by Django 5.0.3 on 2025-06-01 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_modifier_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifier',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='modifier',
            name='requirement',
        ),
        migrations.AddField(
            model_name='modifier',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('unavailable_for_today', 'Unavailable for Today')], default='available', max_length=50),
        ),
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('requirement', models.CharField(choices=[('optional', 'Optional'), ('required', 'Required')], default='optional', max_length=20)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='store.menuitem')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='store.modifier')),
            ],
        ),
    ]
