# Generated by Django 5.0.3 on 2025-06-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_modifier_menu_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifiergroup',
            name='modifier',
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='modifiers',
            field=models.ManyToManyField(related_name='modifier_groups', to='store.modifier'),
        ),
    ]
