# Generated by Django 5.1.2 on 2024-10-24 04:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Order ID')),
                ('client_id', models.CharField(max_length=255, verbose_name='client id')),
                ('platform', models.CharField(choices=[('chatchefs', 'CHATCHEFS'), ('na', 'NA')], default='chatchefs', max_length=50, verbose_name='platform')),
                ('pickup_customer_name', models.CharField(max_length=255, verbose_name='pickup customer name')),
                ('pickup_latitude', models.FloatField(default=0)),
                ('pickup_longitude', models.FloatField(default=0)),
                ('pickup_phone', models.CharField(max_length=20, verbose_name='pickup phone number')),
                ('pickup_ready_at', models.DateTimeField(verbose_name='pickup ready at')),
                ('pickup_last_time', models.DateTimeField(verbose_name='pickup last time')),
                ('drop_off_customer_name', models.CharField(max_length=255, verbose_name='drop of customer name')),
                ('drop_off_latitude', models.FloatField(default=0)),
                ('drop_off_longitude', models.FloatField(default=0)),
                ('drop_off_phone', models.CharField(max_length=20, verbose_name='drop off phone number')),
                ('drop_off_last_time', models.DateTimeField(verbose_name='drop off last time')),
                ('delivery_completed_time', models.DateTimeField(blank=True, null=True, verbose_name='delivery completed time')),
                ('status', models.CharField(choices=[('created', 'CREATED'), ('waiting_for_driver', 'WAITING_FOR_DRIVER'), ('driver_assign', 'DRIVER_ASSIGNED'), ('order_picked_up', 'ORDER_PICKED_UP'), ('on_the_way', 'ON_THE_WAY'), ('delivery_success', 'DELIVERY_SUCCESS'), ('delivery_failed', 'DELIVERY_FAILED'), ('driver_rejected', 'DRIVER_REJECTED')], default='waiting_for_driver', max_length=100, verbose_name='status')),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('CAD', 'CAD'), ('bdt', 'BDT')], default='bdt', max_length=3, verbose_name='currency')),
                ('ride_duration', models.PositiveIntegerField(default=0)),
                ('distance', models.PositiveIntegerField(default=0)),
                ('fees', models.PositiveIntegerField(default=0)),
                ('tips', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('cash_collected', models.PositiveIntegerField(default=0)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('payment_type', models.CharField(choices=[('cash', 'CASH'), ('card', 'CARD')], default='card', max_length=50, verbose_name='payment type')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL, verbose_name='driver')),
                ('drop_off_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.address', verbose_name='pickup address')),
                ('pickup_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_address', to='core.address', verbose_name='pickup address')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
