# Generated by Django 5.1.2 on 2024-10-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_deliveryfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='cash_collected',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='fees',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='ride_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='tips',
            field=models.FloatField(default=0),
        ),
    ]
