# Generated by Django 5.0.3 on 2024-10-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_delivery_amount_alter_delivery_cash_collected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='use_google',
            field=models.BooleanField(default=False),
        ),
    ]
