# Generated by Django 5.0.3 on 2025-02-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_delivery_cancel_reason_delivery_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
