# Generated by Django 5.0.3 on 2025-02-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_delivery_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='driver_earning',
            field=models.FloatField(default=0),
        ),
    ]
