# Generated by Django 5.0.3 on 2025-02-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_delivery_driver_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivered_product_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_product_images'),
        ),
    ]
