# Generated by Django 5.0.3 on 2025-02-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_delivery_delivered_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='use_google',
            field=models.BooleanField(default=True),
        ),
    ]
