# Generated by Django 5.0.3 on 2025-02-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_delivery_use_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='use_google',
            field=models.BooleanField(default=False),
        ),
    ]
