# Generated by Django 5.0.3 on 2025-02-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_delivery_use_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('created', 'CREATED'), ('waiting_for_driver', 'WAITING_FOR_DRIVER'), ('driver_assign', 'DRIVER_ASSIGNED'), ('order_picked_up', 'ORDER_PICKED_UP'), ('on_the_way', 'ON_THE_WAY'), ('arrived', 'ARRIVED'), ('delivery_success', 'DELIVERY_SUCCESS'), ('delivery_failed', 'DELIVERY_FAILED'), ('driver_rejected', 'DRIVER_REJECTED'), ('canceled', 'CANCELED')], default='waiting_for_driver', max_length=100, verbose_name='status'),
        ),
    ]
