# Generated by Django 5.0.3 on 2025-02-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='use_google',
            field=models.BooleanField(default=True),
        ),
    ]
