# Generated by Django 5.0.3 on 2025-02-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_alter_delivery_use_google'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivery_completed_time',
            new_name='est_delivery_completed_time',
        ),
        migrations.AddField(
            model_name='delivery',
            name='actual_delivery_completed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='actual delivery completed time'),
        ),
    ]
