# Generated by Django 5.0.3 on 2025-02-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_rename_delivery_completed_time_delivery_est_delivery_completed_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='est_delivery_completed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='estimated delivery completed time'),
        ),
    ]
