# Generated by Django 5.0.3 on 2025-02-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_alter_delivery_est_delivery_completed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='customer_info',
            field=models.JSONField(default=dict),
        ),
    ]
