# Generated by Django 5.0.3 on 2025-05-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_delivery_customer_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='rider_accepted_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rider Accepted Time'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='rider_pickup_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rider Pickup Time'),
        ),
    ]
