# Generated by Django 5.0.3 on 2025-06-01 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_delivery_rider_accepted_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('reported_by', models.CharField(choices=[('customer', 'Customer'), ('driver', 'Driver'), ('store', 'Store')], default='customer', max_length=20)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='delivery_issue_proofs')),
                ('issue_type', models.CharField(choices=[('missing_item', 'Missing Item'), ('wrong_item', 'Wrong Item'), ('damaged_item', 'Damaged Item'), ('late_delivery', 'Late Delivery'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='Status')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='billing.delivery', verbose_name='Delivery')),
            ],
            options={
                'verbose_name': 'Delivery Issue',
                'verbose_name_plural': 'Delivery Issues',
                'ordering': ['-id'],
            },
        ),
    ]
