# Generated by Django 5.0.3 on 2025-06-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_deliveryissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryissue',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Order ID'),
        ),
    ]
