# Generated by Django 5.0.3 on 2025-06-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_deliveryissue_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryissue',
            name='issue_type',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
