# Generated by Django 5.0.3 on 2025-06-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0018_deliveryissue_order_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryEarningConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_distance_km", models.FloatField(default=10)),
                ("base_earning", models.FloatField(default=25)),
                ("extra_per_km", models.FloatField(default=3)),
                ("grace_period_minutes", models.IntegerField(default=5)),
                ("penalty_6_10", models.FloatField(default=5)),
                ("penalty_11_15", models.FloatField(default=10)),
                ("penalty_above_15", models.FloatField(default=15)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="deliveryissue",
            name="issue_type",
            field=models.CharField(default="other", max_length=50),
        ),
    ]
