# Generated by Django 5.0.3 on 2025-06-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0019_deliveryearningconfig_alter_deliveryissue_issue_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryearningconfig",
            name="estimated_time_per_km",
            field=models.FloatField(default=3.5),
        ),
    ]
