# Generated by Django 5.0.3 on 2025-06-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0019_alter_deliveryissue_issue_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryEarningConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estimated_time_per_km", models.FloatField(default=3.5)),
                ("base_distance_km", models.FloatField(default=10)),
                ("base_earning", models.FloatField(default=25)),
                ("extra_per_km", models.FloatField(default=3)),
                ("grace_period_minutes", models.IntegerField(default=5)),
                ("penalty_6_10", models.FloatField(default=50)),
                ("penalty_11_15", models.FloatField(default=50)),
                ("penalty_above_15", models.FloatField(default=70)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="delivery",
            name="on_time_guarantee_fee",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="delivery",
            name="on_time_guarantee_opted_in",
            field=models.BooleanField(default=False),
        ),
    ]
