# Generated by Django 5.0.3 on 2025-06-17 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0019_alter_deliveryissue_issue_type"),
        ("billing", "0020_deliveryearningconfig_estimated_time_per_km"),
    ]

    operations = []
