# Generated by Django 5.0.3 on 2025-06-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0021_merge_20250617_1559"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryearningconfig",
            name="penalty_11_15",
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name="deliveryearningconfig",
            name="penalty_6_10",
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name="deliveryearningconfig",
            name="penalty_above_15",
            field=models.FloatField(default=70),
        ),
    ]
