# Generated by Django 5.0.3 on 2025-06-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0022_alter_deliveryearningconfig_penalty_11_15_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="on_time_guarantee_fee",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="delivery",
            name="on_time_guarantee_opted_in",
            field=models.BooleanField(default=False),
        ),
    ]
