# Generated by Django 5.0.3 on 2025-06-01 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0017_remove_modifiergroup_modifier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('voucher_type', models.CharField(choices=[('coupon', 'Coupon'), ('percentage', 'Percentage'), ('flat', 'Flat'), ('bxgy', 'Buy X Get Y'), ('bogo', 'Buy One Get One'), ('spend_x_save_y', 'Spend X Save Y')], max_length=20)),
                ('target_type', models.CharField(choices=[('platform', 'Platform'), ('store', 'Store')], help_text='The voucher applies to the entire platform, across all stores or to a specific store.', max_length=10, verbose_name='Target Type')),
                ('responsible_party', models.CharField(choices=[('platform', 'Platform'), ('store', 'Store'), ('shared', 'Shared')], max_length=10)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('usage_limit', models.IntegerField(default=1)),
                ('usage_limit_per_user', models.PositiveIntegerField(blank=True, help_text='Maximum number of times a single user can use this voucher. Leave blank for unlimited.', null=True)),
                ('total_used_count', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store')),
                ('users', models.ManyToManyField(blank=True, related_name='vouchers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher.voucher')),
            ],
            options={
                'unique_together': {('voucher', 'user')},
            },
        ),
    ]
