# Generated by Django 5.0.3 on 2025-06-01 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_modifiergroup_modifier_and_more'),
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('main_price', models.DecimalField(decimal_places=2, default=0, help_text='Base price of the menu item', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total discount amount applied to the item', max_digits=6)),
                ('deal_price', models.DecimalField(decimal_places=2, default=0, help_text='Final price user pays', max_digits=10)),
                ('offer_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat'), ('bogo', 'BOGO')], default='percentage', max_length=20)),
                ('deal_type', models.CharField(choices=[('special_discount', 'Special Discount'), ('normal_discount', 'Normal Discount')], default='normal_discount', help_text='Type of the deal || special discount must be special then normal discount', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('purchase_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('times_purchased', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.menuitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
