# Generated by Django 5.0.3 on 2025-03-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
